// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBelzWMFznc0SaBQ_BLb4DW7lGVA5hRdog',
    appId: '1:47680103422:web:64f9ab3463d150103356af',
    messagingSenderId: '47680103422',
    projectId: 'smartposture-fd189',
    authDomain: 'smartposture-fd189.firebaseapp.com',
    storageBucket: 'smartposture-fd189.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlDP2hiknWoUsclOKHPtOducApw9ytCPs',
    appId: '1:47680103422:android:aa804726585655973356af',
    messagingSenderId: '47680103422',
    projectId: 'smartposture-fd189',
    storageBucket: 'smartposture-fd189.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpYOWjyKi5DzIKq7YqQKPVXKQVRZ0LcFc',
    appId: '1:47680103422:ios:49295d9e383973c23356af',
    messagingSenderId: '47680103422',
    projectId: 'smartposture-fd189',
    storageBucket: 'smartposture-fd189.firebasestorage.app',
    iosBundleId: 'com.example.skripsiAnggi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpYOWjyKi5DzIKq7YqQKPVXKQVRZ0LcFc',
    appId: '1:47680103422:ios:49295d9e383973c23356af',
    messagingSenderId: '47680103422',
    projectId: 'smartposture-fd189',
    storageBucket: 'smartposture-fd189.firebasestorage.app',
    iosBundleId: 'com.example.skripsiAnggi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBelzWMFznc0SaBQ_BLb4DW7lGVA5hRdog',
    appId: '1:47680103422:web:422ec806103163a33356af',
    messagingSenderId: '47680103422',
    projectId: 'smartposture-fd189',
    authDomain: 'smartposture-fd189.firebaseapp.com',
    storageBucket: 'smartposture-fd189.firebasestorage.app',
  );
}
